version: '3.5'  

services: 
    frontend: 
      image: exercise1.10
      ports:
        - 5000:5000
      environment: 
      - API_URL=http://localhost/api
    backend: 
      image: exercise1.11
      ports:
        - 8000:8000
      environment: 
        - FRONT_URL=http://localhost
        - REDIS=redis
        - DB_USERNAME=johndoe
        - DB_PASSWORD=dasjsfbabnfas
        - DB_HOST=db
      depends_on: 
        - db
    redis:
      image: redis
    db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_USER=johndoe
        - POSTGRES_PASSWORD=dasjsfbabnfas
    nginx:
      image: nginx
      volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports: 
        - 80:80
      depends_on:
        - backend
        - frontend